"""
NyayaAI — Phase 3 Corpus Expansion Script
Adds 9 verified provisions across BNS, BNSS, and BSA to seed_corpus.json.
"""

import json
import sys
from pathlib import Path

backend_dir = Path(__file__).resolve().parents[1]
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.models.legal_provision import LegalProvision

NEW_PROVISIONS = [
    {
        "provision_id": "bns-2023-section-85",
        "provision_type": "STATUTORY_SECTION",
        "category": "bns",
        "act": "Bharatiya Nyaya Sanhita, 2023",
        "act_short": "BNS 2023",
        "reference_number": "Section 85",
        "article_number": None,
        "short_title": "Husband or relative of husband of a woman subjecting her to cruelty",
        "title": "Husband or relative of husband of a woman subjecting her to cruelty",
        "part": "Chapter V — Of Offences Against Woman and Child",
        "clause": None,
        "exact_text": "Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 85 of BNS 2023 makes it a criminal offence for a husband or any relative of the husband to subject a woman to cruelty. It provides for punishment of imprisonment up to three years and a fine. Cruelty includes conduct driving the woman to suicide, causing grave injury or danger to life or health, or harassment to coerce unlawful property demands. This replaced Section 498A of the Indian Penal Code, 1860.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20062/1/bharatiya_nyaya_sanhita_2023.pdf",
        "official_citation": "BNS 2023, s. 85",
        "citation": "BNS 2023, s. 85",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nyaya Sanhita, 2023 — in force from 1 July 2024. Replaced IPC s. 498A.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bns-2023-section-86"],
    },
    {
        "provision_id": "bns-2023-section-115",
        "provision_type": "STATUTORY_SECTION",
        "category": "bns",
        "act": "Bharatiya Nyaya Sanhita, 2023",
        "act_short": "BNS 2023",
        "reference_number": "Section 115",
        "article_number": None,
        "short_title": "Voluntarily causing hurt",
        "title": "Voluntarily causing hurt",
        "part": "Chapter VI — Of Offences Affecting the Human Body, Part II — Of Hurt",
        "clause": None,
        "exact_text": "(1) Whoever does any act with the intention of thereby causing hurt to any person, or with the knowledge that he is likely thereby to cause hurt to any person, and does thereby cause hurt to any person, is said 'voluntarily to cause hurt'.\n\n(2) Whoever, except in the case provided for by sub-section (1) of section 122, voluntarily causes hurt, shall be punished with imprisonment of either description for a term which may extend to one year, or with fine which may extend to ten thousand rupees, or with both.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 115 of BNS 2023 defines and punishes the offence of voluntarily causing hurt. Causing bodily pain, disease, or infirmity with the intention or knowledge of doing so is punishable with imprisonment up to one year, a fine up to ten thousand rupees, or both. This replaced Sections 321 and 323 of the Indian Penal Code, 1860.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20062/1/bharatiya_nyaya_sanhita_2023.pdf",
        "official_citation": "BNS 2023, s. 115",
        "citation": "BNS 2023, s. 115",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nyaya Sanhita, 2023 — in force from 1 July 2024. Replaced IPC s. 323.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bns-2023-section-117"],
    },
    {
        "provision_id": "bns-2023-section-117",
        "provision_type": "STATUTORY_SECTION",
        "category": "bns",
        "act": "Bharatiya Nyaya Sanhita, 2023",
        "act_short": "BNS 2023",
        "reference_number": "Section 117",
        "article_number": None,
        "short_title": "Voluntarily causing grievous hurt",
        "title": "Voluntarily causing grievous hurt",
        "part": "Chapter VI — Of Offences Affecting the Human Body, Part II — Of Hurt",
        "clause": None,
        "exact_text": "(1) Whoever voluntarily causes hurt, if the hurt which he intends to cause or knows himself to be likely to cause is grievous hurt, and if the hurt which he causes is grievous hurt, is said 'voluntarily to cause grievous hurt'.\n\n(2) Whoever, except in the case provided for by sub-section (2) of section 122, voluntarily causes grievous hurt, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 117 of BNS 2023 governs the offence of voluntarily causing grievous hurt (such as permanent loss of sight/hearing, bone fracture, or life-endangering injury). The punishment is imprisonment for up to seven years plus a fine. This replaced Sections 322 and 325 of the Indian Penal Code, 1860.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20062/1/bharatiya_nyaya_sanhita_2023.pdf",
        "official_citation": "BNS 2023, s. 117",
        "citation": "BNS 2023, s. 117",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nyaya Sanhita, 2023 — in force from 1 July 2024. Replaced IPC s. 325.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bns-2023-section-115"],
    },
    {
        "provision_id": "bns-2023-section-318",
        "provision_type": "STATUTORY_SECTION",
        "category": "bns",
        "act": "Bharatiya Nyaya Sanhita, 2023",
        "act_short": "BNS 2023",
        "reference_number": "Section 318",
        "article_number": None,
        "short_title": "Cheating",
        "title": "Cheating",
        "part": "Chapter XVII — Of Offences Against Property",
        "clause": None,
        "exact_text": "(1) Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived, and which act or omission causes or is likely to cause damage or harm to that person in body, mind, reputation or property, is said to 'cheat'.\n\n(2) Whoever cheats shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.\n\n(4) Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 318 of BNS 2023 defines and punishes cheating. Simple cheating carries imprisonment up to three years, a fine, or both. Aggravated cheating involving dishonest inducement to deliver property or alter valuable securities (former IPC Section 420) carries rigorous imprisonment up to seven years plus a fine. This consolidated Sections 415, 417, and 420 of the Indian Penal Code, 1860.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20062/1/bharatiya_nyaya_sanhita_2023.pdf",
        "official_citation": "BNS 2023, s. 318",
        "citation": "BNS 2023, s. 318",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nyaya Sanhita, 2023 — in force from 1 July 2024. Replaced IPC ss. 415, 420.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bns-2023-section-303"],
    },
    {
        "provision_id": "bnss-2023-section-43",
        "provision_type": "STATUTORY_SECTION",
        "category": "bnss",
        "act": "Bharatiya Nagarik Suraksha Sanhita, 2023",
        "act_short": "BNSS 2023",
        "reference_number": "Section 43",
        "article_number": None,
        "short_title": "Arrest by private person and procedure on such arrest",
        "title": "Arrest by private person and procedure on such arrest",
        "part": "Chapter V — Arrest of Persons",
        "clause": None,
        "exact_text": "(1) Any private person may arrest or cause to be arrested any person who in his presence commits a non-bailable and cognizable offence, or any proclaimed offender, and, without unnecessary delay, shall hand over or cause to be handed over any person so arrested to a police officer, or in the absence of a police officer, take such person or cause him to be taken in custody to the nearest police station.\n\n(2) If there is reason to believe that such person comes under the provisions of section 35, a police officer shall re-arrest him.\n\n(3) If there is reason to believe that he has committed a non-cognizable offence, and he refuses on the demand of a police officer to give his name and residence, or gives a name or residence which such officer has reason to believe to be false, he shall be dealt with under the provisions of section 39; but if there is no sufficient reason to believe that he has committed any offence, he shall be at once released.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 43 of BNSS 2023 grants ordinary citizens the legal right to make an arrest ('citizen arrest') if someone commits a non-bailable and cognizable offence in their presence, or if the person is a proclaimed offender. The arrested person must be handed over without unnecessary delay to a police officer or taken to the nearest police station. This replaced Section 43 of the Code of Criminal Procedure, 1973.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20063/1/bharatiya_nagarik_suraksha_sanhita_2023.pdf",
        "official_citation": "BNSS 2023, s. 43",
        "citation": "BNSS 2023, s. 43",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nagarik Suraksha Sanhita, 2023 — in force from 1 July 2024. Replaced CrPC 1973, s. 43.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bnss-2023-section-35"],
    },
    {
        "provision_id": "bnss-2023-section-126",
        "provision_type": "STATUTORY_SECTION",
        "category": "bnss",
        "act": "Bharatiya Nagarik Suraksha Sanhita, 2023",
        "act_short": "BNSS 2023",
        "reference_number": "Section 126",
        "article_number": None,
        "short_title": "Order for maintenance of wives, children and parents",
        "title": "Order for maintenance of wives, children and parents",
        "part": "Chapter X — Maintenance of Wives, Children and Parents",
        "clause": None,
        "exact_text": "(1) If any person having sufficient means neglects or refuses to maintain—\n(a) his wife, unable to maintain herself, or\n(b) his legitimate or illegitimate minor child, whether married or not, unable to maintain itself, or\n(c) his legitimate or illegitimate child (not being a married daughter) who has attained majority, where such child is, by reason of any physical or mental abnormality or injury unable to maintain itself, or\n(d) his father or mother, unable to maintain himself or herself,\na Magistrate of the first class may, upon proof of such neglect or refusal, order such person to make a monthly allowance for the maintenance of his wife or such child, father or mother, at such monthly rate as such Magistrate thinks fit and to pay the same to such person as the Magistrate may from time to time direct.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 126 of BNSS 2023 provides a statutory mechanism for wives, minor children, disabled adult children, and elderly parents to claim monthly maintenance from a person with sufficient means who neglects or refuses to support them. It provides swift financial relief to prevent destitution. This replaced Section 125 of the Code of Criminal Procedure, 1973.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20063/1/bharatiya_nagarik_suraksha_sanhita_2023.pdf",
        "official_citation": "BNSS 2023, s. 126",
        "citation": "BNSS 2023, s. 126",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nagarik Suraksha Sanhita, 2023 — in force from 1 July 2024. Replaced CrPC 1973, s. 125.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bnss-2023-section-2"],
    },
    {
        "provision_id": "bnss-2023-section-480",
        "provision_type": "STATUTORY_SECTION",
        "category": "bnss",
        "act": "Bharatiya Nagarik Suraksha Sanhita, 2023",
        "act_short": "BNSS 2023",
        "reference_number": "Section 480",
        "article_number": None,
        "short_title": "When bail may be taken in case of non-bailable offence",
        "title": "When bail may be taken in case of non-bailable offence",
        "part": "Chapter XXXV — Bail and Bail Bonds",
        "clause": None,
        "exact_text": "(1) When any person accused of, or suspected of, the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police station or appears or is brought before a Court other than the High Court or Court of Session, he may be released on bail, but—\n(i) such person shall not be so released if there appear reasonable grounds for believing that he has been guilty of an offence punishable with death or imprisonment for life;\n(ii) such person shall not be so released if such offence is a cognizable offence and he had been previously convicted of an offence punishable with death, imprisonment for life or imprisonment for seven years or more, or he had been previously convicted on two or more occasions of a cognizable offence punishable with imprisonment for three years or more but not less than seven years:\n\nProvided that the Court may direct that a person referred to in clause (i) or clause (ii) be released on bail if such person is under the age of sixteen years or is a woman or is sick or infirm.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 480 of BNSS 2023 governs regular bail in non-bailable offences by magistrate courts. Bail is withheld if there are reasonable grounds to believe the accused committed an offence punishable with death or life imprisonment, or is a repeat offender. However, courts hold statutory discretion to grant bail if the accused is a woman, child under 16, or sick/infirm. This replaced Section 437 of the Code of Criminal Procedure, 1973.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20063/1/bharatiya_nagarik_suraksha_sanhita_2023.pdf",
        "official_citation": "BNSS 2023, s. 480",
        "citation": "BNSS 2023, s. 480",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nagarik Suraksha Sanhita, 2023 — in force from 1 July 2024. Replaced CrPC 1973, s. 437.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bnss-2023-section-479", "bnss-2023-section-482"],
    },
    {
        "provision_id": "bnss-2023-section-482",
        "provision_type": "STATUTORY_SECTION",
        "category": "bnss",
        "act": "Bharatiya Nagarik Suraksha Sanhita, 2023",
        "act_short": "BNSS 2023",
        "reference_number": "Section 482",
        "article_number": None,
        "short_title": "Direction for grant of bail to person apprehending arrest — Anticipatory Bail",
        "title": "Direction for grant of bail to person apprehending arrest",
        "part": "Chapter XXXV — Bail and Bail Bonds",
        "clause": None,
        "exact_text": "(1) Where any person has reason to believe that he may be arrested on accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction under this section that in the event of such arrest he shall be released on bail; and that Court may, after taking into consideration, inter alia, the following factors, namely:—\n(i) the nature and gravity of the accusation;\n(ii) the antecedents of the applicant including the fact as to whether he has previously undergone imprisonment on conviction by a Court in respect of any cognizable offence;\n(iii) the possibility of the applicant to flee from justice; and\n(iv) where the accusation has been made with the object of injuring or humiliating the applicant by having him so arrested,\neither reject the application forthwith or issue an interim order for the grant of anticipatory bail.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 482 of BNSS 2023 provides for anticipatory bail (pre-arrest bail). A person apprehending arrest in a non-bailable case may petition the High Court or Sessions Court for protection. The court considers the nature of allegations, criminal history, flight risk, and whether the accusation was filed maliciously to humiliate the applicant. This replaced Section 438 of the Code of Criminal Procedure, 1973.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20063/1/bharatiya_nagarik_suraksha_sanhita_2023.pdf",
        "official_citation": "BNSS 2023, s. 482",
        "citation": "BNSS 2023, s. 482",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Nagarik Suraksha Sanhita, 2023 — in force from 1 July 2024. Replaced CrPC 1973, s. 438.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bnss-2023-section-479", "bnss-2023-section-480"],
    },
    {
        "provision_id": "bsa-2023-section-24",
        "provision_type": "STATUTORY_SECTION",
        "category": "bsa",
        "act": "Bharatiya Sakshya Adhiniyam, 2023",
        "act_short": "BSA 2023",
        "reference_number": "Section 24",
        "article_number": None,
        "short_title": "Confession caused by inducement, threat or promise, when irrelevant in criminal proceeding",
        "title": "Confession caused by inducement, threat or promise, when irrelevant in criminal proceeding",
        "part": "Part II — Of the Relevancy of Facts, Chapter III — Admissions and Confessions",
        "clause": None,
        "exact_text": "A confession made by an accused person is irrelevant in a criminal proceeding, if the making of the confession appears to the Court to have been caused by any inducement, threat or promise, having reference to the charge against the accused person, proceeding from a person in authority and sufficient, in the opinion of the Court, to give the accused person grounds, which would appear to him reasonable, for supposing that by making it he would gain any advantage or avoid any evil of a temporal nature in reference to the proceedings against him.",
        "exact_text_language": "en",
        "language": "English",
        "ai_explanation": "Section 24 of BSA 2023 establishes that a confession given by an accused person is inadmissible and irrelevant in a criminal trial if it was obtained through any inducement, threat, or promise made by a person in authority (such as police). This fundamental evidence safeguard bars involuntary or coerced confessions. This replaced Section 24 of the Indian Evidence Act, 1872.",
        "source_name": "Ministry of Law and Justice, Legislative Department, Government of India",
        "source_type": "official",
        "source_authority": "Government of India",
        "source_url": "https://indiacode.nic.in/bitstream/123456789/20064/1/bharatiya_sakshya_adhiniyam_2023.pdf",
        "official_citation": "BSA 2023, s. 24",
        "citation": "BSA 2023, s. 24",
        "verification_status": "verified",
        "text_source": "india_code_manual",
        "last_verified": "2026-09-13",
        "effective_date": "2024-07-01",
        "effective_from": "2024-07-01",
        "effective_to": None,
        "is_current_law": True,
        "supersedes": None,
        "superseded_by": None,
        "version_note": "Bharatiya Sakshya Adhiniyam, 2023 — in force from 1 July 2024. Replaced Indian Evidence Act 1872, s. 24.",
        "jurisdiction": "central",
        "applicable_states": [],
        "related_provisions": ["bsa-2023-section-2"],
    },
]


def main():
    corpus_file = backend_dir / "data" / "seed_corpus.json"
    with open(corpus_file, "r", encoding="utf-8") as f:
        corpus = json.load(f)

    print(f"Existing provisions count: {len(corpus)}")

    # Validate each new provision
    for p in NEW_PROVISIONS:
        LegalProvision.model_validate(p)

    corpus.extend(NEW_PROVISIONS)

    # Check uniqueness
    ids = [x["provision_id"] for x in corpus]
    refs = [x["reference_number"] for x in corpus]
    assert len(ids) == len(set(ids)), f"Duplicate provision_ids detected: {len(ids)} vs {len(set(ids))}"
    assert len(refs) == len(set(refs)), f"Duplicate reference_numbers detected: {len(refs)} vs {len(set(refs))}"

    with open(corpus_file, "w", encoding="utf-8") as f:
        json.dump(corpus, f, indent=2, ensure_ascii=False)

    print(f"Successfully updated {corpus_file} with {len(corpus)} total provisions!")


if __name__ == "__main__":
    main()
