"""
NyayaAI — Legal Provision Service

Phase 1:
Loads the curated legal seed corpus and provides safe lookup/search.
Exact legal text is returned from the corpus and is never generated by AI.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from app.models.legal_provision import (
    LegalProvision,
    ProvisionCategory,
)


class LegalProvisionService:
    """Service for retrieving verified legal provisions from the local corpus."""

    def __init__(self) -> None:
        self.corpus_path = (
            Path(__file__).resolve().parents[2] / "data" / "seed_corpus.json"
        )
        self._provisions: list[LegalProvision] = []
        self._load_corpus()

    def _load_corpus(self) -> None:
        """Load and validate the local seed corpus."""
        if not self.corpus_path.exists():
            raise FileNotFoundError(
                f"Legal seed corpus not found: {self.corpus_path}"
            )

        with self.corpus_path.open("r", encoding="utf-8") as file:
            data = json.load(file)

        # Support either a direct list or {"provisions": [...]}
        if isinstance(data, list):
            records = data
        elif isinstance(data, dict):
            records = data.get("provisions", [])
        else:
            raise ValueError("Invalid seed corpus format.")

        self._provisions = [
            LegalProvision.model_validate(record)
            for record in records
        ]

    def get_all(self) -> list[LegalProvision]:
        """Return all provisions in the local corpus."""
        return self._provisions.copy()

    def get_by_id(self, provision_id: str) -> Optional[LegalProvision]:
        """Return one provision by its stable ID."""
        for provision in self._provisions:
            if provision.provision_id == provision_id:
                return provision

        return None

    def get_by_reference(
        self,
        reference_number: str,
    ) -> Optional[LegalProvision]:
        """Return a provision by Article/Section reference."""
        reference = reference_number.strip().lower()

        for provision in self._provisions:
            if provision.reference_number.lower() == reference:
                return provision

        return None

    def search(
        self,
        query: str,
        category: Optional[ProvisionCategory] = None,
    ) -> list[LegalProvision]:
        """
        Simple Phase-1 keyword search.

        RAG/semantic retrieval will be added separately in the next phase.
        """
        query = query.strip().lower()

        if not query:
            return []

        results: list[LegalProvision] = []

        for provision in self._provisions:
            searchable_text = " ".join(
                [
                    provision.reference_number,
                    provision.short_title,
                    provision.title or "",
                    provision.act,
                    provision.act_short,
                    provision.exact_text,
                    provision.ai_explanation or "",
                ]
            ).lower()

            if query in searchable_text:
                if category is None or provision.category == category:
                    results.append(provision)

        return results