"""
NyayaAI — RAG Service

Phase 1:
Provides ChromaDB-backed retrieval over the verified legal corpus.

Important:
- ChromaDB identifies relevant provisions.
- LegalProvisionService remains the source of truth for legal text.
- Exact legal text is never generated by AI.
"""

from __future__ import annotations

from typing import Optional

import chromadb

from app.core.config import settings
from app.models.legal_provision import (
    LegalProvision,
    ProvisionCategory,
)
from app.services.legal_provision_service import LegalProvisionService


class RAGService:
    """ChromaDB retrieval service for legal provisions."""

    def __init__(self) -> None:
        self.client = chromadb.PersistentClient(
            path=settings.chroma_persist_directory
        )

        self.collection = self.client.get_or_create_collection(
            name=settings.chroma_collection_name
        )

        self.legal_service = LegalProvisionService()

    def collection_count(self) -> int:
        """Return the number of indexed legal provisions."""
        return self.collection.count()

    def index_provisions(
        self,
        provisions: list[LegalProvision],
    ) -> int:
        """Index legal provisions into ChromaDB."""

        if not provisions:
            return 0

        ids = []
        documents = []
        metadatas = []

        for provision in provisions:
            ids.append(provision.provision_id)

            documents.append(
                "\n".join(
                    [
                        provision.reference_number,
                        provision.short_title,
                        provision.title or "",
                        provision.act,
                        provision.act_short,
                        provision.exact_text,
                        provision.ai_explanation or "",
                    ]
                )
            )

            metadatas.append(
                {
                    "provision_id": provision.provision_id,
                    "reference_number": provision.reference_number,
                    "category": provision.category.value,
                    "jurisdiction": provision.jurisdiction.value,
                    "verification_status": (
                        provision.verification_status.value
                    ),
                    "source_type": provision.source_type.value,
                    "is_current_law": provision.is_current_law,
                }
            )

        self.collection.upsert(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
        )

        return len(provisions)

    def search(
        self,
        query: str,
        category: Optional[ProvisionCategory] = None,
        top_k: int = 5,
        max_distance: float = 1.5,
    ) -> list[dict]:
        """
        Retrieve relevant legal provisions with a confidence threshold.

        ChromaDB determines which provision IDs are relevant.
        LegalProvisionService supplies the verified legal content.

        Results with a distance greater than max_distance are rejected
        so weak retrieval does not become a confident legal answer.
        """

        query = query.strip()

        if not query:
            return []

        if top_k < 1:
            return []

        where = None

        if category is not None:
            where = {
                "category": category.value,
            }

        results = self.collection.query(
            query_texts=[query],
            n_results=top_k,
            where=where,
        )

        retrieved: list[dict] = []

        ids = results.get("ids", [[]])[0]
        distances = results.get("distances", [[]])[0]

        for index, provision_id in enumerate(ids):
            distance = (
                distances[index]
                if index < len(distances)
                else None
            )

            if distance is None:
                continue

            if distance > max_distance:
                continue

            provision = self.legal_service.get_by_id(provision_id)

            if provision is None:
                continue

            retrieved.append(
                {
                    "provision": provision,
                    "distance": distance,
                }
            )

        return retrieved